./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &
./small-bazooka.sh &

